<?php
// $Id$
/**
 * @file
 * Hooks and API functions for Data UI module.
 */

/**
 * Implementation of hook_menu()
 */
function data_ui_menu() {
  $items = array();
  $items['admin/content/data'] = array(
    'title' => 'Data tables',
    'description' => 'Administer data tables.',
    'page callback' => 'data_ui_overview',
    'file' => 'data_ui.admin.inc',
    'access arguments' => array('administer data tables'),
  );
  $items['admin/content/data/overview'] = array(
    'title' => 'Overview',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/content/data/compare'] = array(
    'title' => 'Compare schemas',
    'description' => 'Administer data tables.',
    'page callback' => 'data_ui_compare',
    'file' => 'data_ui.admin.inc',
    'access arguments' => array('administer data tables'), 
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/data/create'] = array(
    'title' => 'Create a table',
    'description' => 'Create a data table.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('data_ui_create_form'),
    'file' => 'data_ui.admin.inc',
    'access arguments' => array('administer data tables'),
    'type' => MENU_CALLBACK, 
  );
  $items['admin/content/data/drop/%data_ui_table'] = array(
    'title' => 'Drop table',
    'description' => 'Drop a data table.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('data_ui_drop_form', 4),
    'file' => 'data_ui.admin.inc',
    'access arguments' => array('administer data tables'),
    'type' => MENU_CALLBACK, 
  );
  $items['admin/content/data/edit/%data_ui_table'] = array(
    'title' => 'Data table',
    'description' => 'Administer data tables.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('data_ui_edit_form', 4),
    'file' => 'data_ui.admin.inc',
    'access arguments' => array('administer data tables'),
    'type' => MENU_CALLBACK, 
  );
  $items['admin/content/data/revert/%data_ui_table'] = array(
    'title' => 'Revert data table',
    'description' => 'Administer data tables.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('data_ui_revert_form', 4),
    'file' => 'data_ui.admin.inc',
    'access arguments' => array('administer data tables'),
    'type' => MENU_CALLBACK, 
  );
  $items['admin/content/data/export/%data_ui_table'] = array(
    'title' => 'Data table',
    'description' => 'Export data table.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('data_ui_export_form', 4),
    'file' => 'data_ui.admin.inc',
    'access arguments' => array('administer data tables'),
    'type' => MENU_CALLBACK, 
  );
  return $items;
}

/**
 * Menu loader callback.
 */
function data_ui_table_load($table_name) {
  return data_get_table($table_name);
}

/**
 * Implementation of hook_views_api().
 */
function data_ui_views_api() {
  return array(
    'api' => '2.0',
  );
}

/**
 * Implementation of hook_theme()
 */
function data_ui_theme() {
  return array(
    'data_ui_edit_form' => array(
      'arguments' => array('form' => array()),
    ),
    'data_ui_add_form' => array(
      'arguments' => array('form' => array()),
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function data_ui_perm() {
  return array('administer data tables');
}

/**
 * Creates the default path for a data table.
 */
function data_ui_get_default_path($name) {
  if ($table = data_get_table($name)) {
    // Check, whether there is a data mananged table to the left.
    // @todo: go all the way to the left.
    $path = '';
    $meta = $table->get('meta');
    if (isset($meta['join']) && is_array($meta['join'])) {
      $left_table_name = key($meta['join']);
      if ($left_table = data_get_table($left_table_name)) {
        $path .= $left_table_name .'/';
      }
    }
    return 'admin/content/data/view/'. $path . $name;
  }
  return '';
}